name: WGAN

seed: 42
device: cuda

data_dir: /home/ubuntu/pytorch-gan-zoo/.data/img_align_celeba

z_dim: 128
imsize: 64
img_ch: 3

c: 0.01
n_critic: 5

lr:
  g: 5.0e-5
  d: 5.0e-5

batch_size: 256
epochs: 100
viz_freq: 350
ckpt_freq: 25
